CREATE TABLE brand (
  ID BIGINT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL
);

CREATE TABLE product (
  ID BIGINT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL
);

CREATE TABLE price (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID BIGINT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID BIGINT,
    PRIORITY INT,
    PRICE DECIMAL(10, 2),
    CURRENCY VARCHAR(3),
    CONSTRAINT fk_price_brand FOREIGN KEY (brand_id) REFERENCES brand (id),
    CONSTRAINT fk_price_product FOREIGN KEY (product_id) REFERENCES product (id)
);